#!/bin/sh
# Create the index.html files in the subdirectories

top=`pwd`

directories=`ls -1d [01B]*`
for directory in $directories
do
	cd $directory
	cat > index.html <<EoF
<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <title>$directory Figures for Lee & Seshia </title>
<link href="../../../default.css" rel="stylesheet" type="text/css">
</head>
<body>
<h1>$directory Figures for Lee & Seshia</h1>
<ul>
EoF

	files=`ls -1 *.pdf`
	for file in $files
	do
	    echo " <li><a href=\"$file\">$file</a></li>" >> index.html
	done

	cat >> index.html <<EoF2
</ul>
<p><a href="../index.html">Up</a></p>
</body>
</html>
EoF2

	cd $top
done