# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/AUT/RCS/HW2/HW/Sobel_Edge_Detector_PS/Sobel_Edge_Detector_PS/Sobel_Edge_Detector_PS.srcs/sources_1/bd/design_1/ip/design_1_sobel_edge_detector_0_2/design_1_sobel_edge_detector_0_2.xci
# IP: The module: 'design_1_sobel_edge_detector_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/AUT/RCS/HW2/HW/Sobel_Edge_Detector_PS/Sobel_Edge_Detector_PS/Sobel_Edge_Detector_PS.gen/sources_1/bd/design_1/ip/design_1_sobel_edge_detector_0_2/constraints/sobel_edge_detector_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sobel_edge_detector_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/AUT/RCS/HW2/HW/Sobel_Edge_Detector_PS/Sobel_Edge_Detector_PS/Sobel_Edge_Detector_PS.srcs/sources_1/bd/design_1/ip/design_1_sobel_edge_detector_0_2/design_1_sobel_edge_detector_0_2.xci
# IP: The module: 'design_1_sobel_edge_detector_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/AUT/RCS/HW2/HW/Sobel_Edge_Detector_PS/Sobel_Edge_Detector_PS/Sobel_Edge_Detector_PS.gen/sources_1/bd/design_1/ip/design_1_sobel_edge_detector_0_2/constraints/sobel_edge_detector_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sobel_edge_detector_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
