// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_cnn_Pipeline_clone_for_rows_clone_for_cols (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pad_img0_address0,
        pad_img0_ce0,
        pad_img0_q0,
        pad_img1_address0,
        pad_img1_ce0,
        pad_img1_we0,
        pad_img1_d0,
        pad_img2_address0,
        pad_img2_ce0,
        pad_img2_we0,
        pad_img2_d0,
        pad_img3_address0,
        pad_img3_ce0,
        pad_img3_we0,
        pad_img3_d0,
        pad_img3_1_address0,
        pad_img3_1_ce0,
        pad_img3_1_we0,
        pad_img3_1_d0,
        pad_img3_2_address0,
        pad_img3_2_ce0,
        pad_img3_2_we0,
        pad_img3_2_d0,
        pad_img3_3_address0,
        pad_img3_3_ce0,
        pad_img3_3_we0,
        pad_img3_3_d0,
        pad_img3_4_address0,
        pad_img3_4_ce0,
        pad_img3_4_we0,
        pad_img3_4_d0,
        pad_img3_5_address0,
        pad_img3_5_ce0,
        pad_img3_5_we0,
        pad_img3_5_d0,
        pad_img3_6_address0,
        pad_img3_6_ce0,
        pad_img3_6_we0,
        pad_img3_6_d0,
        pad_img3_7_address0,
        pad_img3_7_ce0,
        pad_img3_7_we0,
        pad_img3_7_d0,
        pad_img3_8_address0,
        pad_img3_8_ce0,
        pad_img3_8_we0,
        pad_img3_8_d0,
        pad_img3_9_address0,
        pad_img3_9_ce0,
        pad_img3_9_we0,
        pad_img3_9_d0,
        pad_img3_10_address0,
        pad_img3_10_ce0,
        pad_img3_10_we0,
        pad_img3_10_d0,
        pad_img3_11_address0,
        pad_img3_11_ce0,
        pad_img3_11_we0,
        pad_img3_11_d0,
        pad_img3_12_address0,
        pad_img3_12_ce0,
        pad_img3_12_we0,
        pad_img3_12_d0,
        pad_img3_13_address0,
        pad_img3_13_ce0,
        pad_img3_13_we0,
        pad_img3_13_d0,
        pad_img3_14_address0,
        pad_img3_14_ce0,
        pad_img3_14_we0,
        pad_img3_14_d0,
        pad_img3_15_address0,
        pad_img3_15_ce0,
        pad_img3_15_we0,
        pad_img3_15_d0,
        pad_img3_16_address0,
        pad_img3_16_ce0,
        pad_img3_16_we0,
        pad_img3_16_d0,
        pad_img3_17_address0,
        pad_img3_17_ce0,
        pad_img3_17_we0,
        pad_img3_17_d0,
        pad_img3_18_address0,
        pad_img3_18_ce0,
        pad_img3_18_we0,
        pad_img3_18_d0,
        pad_img3_19_address0,
        pad_img3_19_ce0,
        pad_img3_19_we0,
        pad_img3_19_d0,
        pad_img3_20_address0,
        pad_img3_20_ce0,
        pad_img3_20_we0,
        pad_img3_20_d0,
        pad_img3_21_address0,
        pad_img3_21_ce0,
        pad_img3_21_we0,
        pad_img3_21_d0,
        pad_img3_22_address0,
        pad_img3_22_ce0,
        pad_img3_22_we0,
        pad_img3_22_d0,
        pad_img3_23_address0,
        pad_img3_23_ce0,
        pad_img3_23_we0,
        pad_img3_23_d0,
        pad_img3_24_address0,
        pad_img3_24_ce0,
        pad_img3_24_we0,
        pad_img3_24_d0,
        pad_img3_25_address0,
        pad_img3_25_ce0,
        pad_img3_25_we0,
        pad_img3_25_d0,
        pad_img3_26_address0,
        pad_img3_26_ce0,
        pad_img3_26_we0,
        pad_img3_26_d0,
        pad_img3_27_address0,
        pad_img3_27_ce0,
        pad_img3_27_we0,
        pad_img3_27_d0,
        pad_img3_28_address0,
        pad_img3_28_ce0,
        pad_img3_28_we0,
        pad_img3_28_d0,
        pad_img3_29_address0,
        pad_img3_29_ce0,
        pad_img3_29_we0,
        pad_img3_29_d0,
        pad_img3_30_address0,
        pad_img3_30_ce0,
        pad_img3_30_we0,
        pad_img3_30_d0,
        pad_img3_31_address0,
        pad_img3_31_ce0,
        pad_img3_31_we0,
        pad_img3_31_d0,
        pad_img3_32_address0,
        pad_img3_32_ce0,
        pad_img3_32_we0,
        pad_img3_32_d0,
        pad_img3_33_address0,
        pad_img3_33_ce0,
        pad_img3_33_we0,
        pad_img3_33_d0,
        pad_img3_34_address0,
        pad_img3_34_ce0,
        pad_img3_34_we0,
        pad_img3_34_d0,
        pad_img3_35_address0,
        pad_img3_35_ce0,
        pad_img3_35_we0,
        pad_img3_35_d0,
        pad_img3_36_address0,
        pad_img3_36_ce0,
        pad_img3_36_we0,
        pad_img3_36_d0,
        pad_img3_37_address0,
        pad_img3_37_ce0,
        pad_img3_37_we0,
        pad_img3_37_d0,
        pad_img3_38_address0,
        pad_img3_38_ce0,
        pad_img3_38_we0,
        pad_img3_38_d0,
        pad_img3_39_address0,
        pad_img3_39_ce0,
        pad_img3_39_we0,
        pad_img3_39_d0,
        pad_img3_40_address0,
        pad_img3_40_ce0,
        pad_img3_40_we0,
        pad_img3_40_d0,
        pad_img3_41_address0,
        pad_img3_41_ce0,
        pad_img3_41_we0,
        pad_img3_41_d0,
        pad_img3_42_address0,
        pad_img3_42_ce0,
        pad_img3_42_we0,
        pad_img3_42_d0,
        pad_img3_43_address0,
        pad_img3_43_ce0,
        pad_img3_43_we0,
        pad_img3_43_d0,
        pad_img3_44_address0,
        pad_img3_44_ce0,
        pad_img3_44_we0,
        pad_img3_44_d0,
        pad_img3_45_address0,
        pad_img3_45_ce0,
        pad_img3_45_we0,
        pad_img3_45_d0,
        pad_img3_46_address0,
        pad_img3_46_ce0,
        pad_img3_46_we0,
        pad_img3_46_d0,
        pad_img3_47_address0,
        pad_img3_47_ce0,
        pad_img3_47_we0,
        pad_img3_47_d0,
        pad_img3_48_address0,
        pad_img3_48_ce0,
        pad_img3_48_we0,
        pad_img3_48_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] pad_img0_address0;
output   pad_img0_ce0;
input  [31:0] pad_img0_q0;
output  [10:0] pad_img1_address0;
output   pad_img1_ce0;
output   pad_img1_we0;
output  [31:0] pad_img1_d0;
output  [10:0] pad_img2_address0;
output   pad_img2_ce0;
output   pad_img2_we0;
output  [31:0] pad_img2_d0;
output  [4:0] pad_img3_address0;
output   pad_img3_ce0;
output   pad_img3_we0;
output  [31:0] pad_img3_d0;
output  [4:0] pad_img3_1_address0;
output   pad_img3_1_ce0;
output   pad_img3_1_we0;
output  [31:0] pad_img3_1_d0;
output  [4:0] pad_img3_2_address0;
output   pad_img3_2_ce0;
output   pad_img3_2_we0;
output  [31:0] pad_img3_2_d0;
output  [4:0] pad_img3_3_address0;
output   pad_img3_3_ce0;
output   pad_img3_3_we0;
output  [31:0] pad_img3_3_d0;
output  [4:0] pad_img3_4_address0;
output   pad_img3_4_ce0;
output   pad_img3_4_we0;
output  [31:0] pad_img3_4_d0;
output  [4:0] pad_img3_5_address0;
output   pad_img3_5_ce0;
output   pad_img3_5_we0;
output  [31:0] pad_img3_5_d0;
output  [4:0] pad_img3_6_address0;
output   pad_img3_6_ce0;
output   pad_img3_6_we0;
output  [31:0] pad_img3_6_d0;
output  [4:0] pad_img3_7_address0;
output   pad_img3_7_ce0;
output   pad_img3_7_we0;
output  [31:0] pad_img3_7_d0;
output  [4:0] pad_img3_8_address0;
output   pad_img3_8_ce0;
output   pad_img3_8_we0;
output  [31:0] pad_img3_8_d0;
output  [4:0] pad_img3_9_address0;
output   pad_img3_9_ce0;
output   pad_img3_9_we0;
output  [31:0] pad_img3_9_d0;
output  [4:0] pad_img3_10_address0;
output   pad_img3_10_ce0;
output   pad_img3_10_we0;
output  [31:0] pad_img3_10_d0;
output  [4:0] pad_img3_11_address0;
output   pad_img3_11_ce0;
output   pad_img3_11_we0;
output  [31:0] pad_img3_11_d0;
output  [4:0] pad_img3_12_address0;
output   pad_img3_12_ce0;
output   pad_img3_12_we0;
output  [31:0] pad_img3_12_d0;
output  [4:0] pad_img3_13_address0;
output   pad_img3_13_ce0;
output   pad_img3_13_we0;
output  [31:0] pad_img3_13_d0;
output  [4:0] pad_img3_14_address0;
output   pad_img3_14_ce0;
output   pad_img3_14_we0;
output  [31:0] pad_img3_14_d0;
output  [4:0] pad_img3_15_address0;
output   pad_img3_15_ce0;
output   pad_img3_15_we0;
output  [31:0] pad_img3_15_d0;
output  [4:0] pad_img3_16_address0;
output   pad_img3_16_ce0;
output   pad_img3_16_we0;
output  [31:0] pad_img3_16_d0;
output  [4:0] pad_img3_17_address0;
output   pad_img3_17_ce0;
output   pad_img3_17_we0;
output  [31:0] pad_img3_17_d0;
output  [4:0] pad_img3_18_address0;
output   pad_img3_18_ce0;
output   pad_img3_18_we0;
output  [31:0] pad_img3_18_d0;
output  [4:0] pad_img3_19_address0;
output   pad_img3_19_ce0;
output   pad_img3_19_we0;
output  [31:0] pad_img3_19_d0;
output  [4:0] pad_img3_20_address0;
output   pad_img3_20_ce0;
output   pad_img3_20_we0;
output  [31:0] pad_img3_20_d0;
output  [4:0] pad_img3_21_address0;
output   pad_img3_21_ce0;
output   pad_img3_21_we0;
output  [31:0] pad_img3_21_d0;
output  [4:0] pad_img3_22_address0;
output   pad_img3_22_ce0;
output   pad_img3_22_we0;
output  [31:0] pad_img3_22_d0;
output  [4:0] pad_img3_23_address0;
output   pad_img3_23_ce0;
output   pad_img3_23_we0;
output  [31:0] pad_img3_23_d0;
output  [4:0] pad_img3_24_address0;
output   pad_img3_24_ce0;
output   pad_img3_24_we0;
output  [31:0] pad_img3_24_d0;
output  [4:0] pad_img3_25_address0;
output   pad_img3_25_ce0;
output   pad_img3_25_we0;
output  [31:0] pad_img3_25_d0;
output  [4:0] pad_img3_26_address0;
output   pad_img3_26_ce0;
output   pad_img3_26_we0;
output  [31:0] pad_img3_26_d0;
output  [4:0] pad_img3_27_address0;
output   pad_img3_27_ce0;
output   pad_img3_27_we0;
output  [31:0] pad_img3_27_d0;
output  [4:0] pad_img3_28_address0;
output   pad_img3_28_ce0;
output   pad_img3_28_we0;
output  [31:0] pad_img3_28_d0;
output  [4:0] pad_img3_29_address0;
output   pad_img3_29_ce0;
output   pad_img3_29_we0;
output  [31:0] pad_img3_29_d0;
output  [4:0] pad_img3_30_address0;
output   pad_img3_30_ce0;
output   pad_img3_30_we0;
output  [31:0] pad_img3_30_d0;
output  [4:0] pad_img3_31_address0;
output   pad_img3_31_ce0;
output   pad_img3_31_we0;
output  [31:0] pad_img3_31_d0;
output  [4:0] pad_img3_32_address0;
output   pad_img3_32_ce0;
output   pad_img3_32_we0;
output  [31:0] pad_img3_32_d0;
output  [4:0] pad_img3_33_address0;
output   pad_img3_33_ce0;
output   pad_img3_33_we0;
output  [31:0] pad_img3_33_d0;
output  [4:0] pad_img3_34_address0;
output   pad_img3_34_ce0;
output   pad_img3_34_we0;
output  [31:0] pad_img3_34_d0;
output  [4:0] pad_img3_35_address0;
output   pad_img3_35_ce0;
output   pad_img3_35_we0;
output  [31:0] pad_img3_35_d0;
output  [4:0] pad_img3_36_address0;
output   pad_img3_36_ce0;
output   pad_img3_36_we0;
output  [31:0] pad_img3_36_d0;
output  [4:0] pad_img3_37_address0;
output   pad_img3_37_ce0;
output   pad_img3_37_we0;
output  [31:0] pad_img3_37_d0;
output  [4:0] pad_img3_38_address0;
output   pad_img3_38_ce0;
output   pad_img3_38_we0;
output  [31:0] pad_img3_38_d0;
output  [4:0] pad_img3_39_address0;
output   pad_img3_39_ce0;
output   pad_img3_39_we0;
output  [31:0] pad_img3_39_d0;
output  [4:0] pad_img3_40_address0;
output   pad_img3_40_ce0;
output   pad_img3_40_we0;
output  [31:0] pad_img3_40_d0;
output  [4:0] pad_img3_41_address0;
output   pad_img3_41_ce0;
output   pad_img3_41_we0;
output  [31:0] pad_img3_41_d0;
output  [4:0] pad_img3_42_address0;
output   pad_img3_42_ce0;
output   pad_img3_42_we0;
output  [31:0] pad_img3_42_d0;
output  [4:0] pad_img3_43_address0;
output   pad_img3_43_ce0;
output   pad_img3_43_we0;
output  [31:0] pad_img3_43_d0;
output  [4:0] pad_img3_44_address0;
output   pad_img3_44_ce0;
output   pad_img3_44_we0;
output  [31:0] pad_img3_44_d0;
output  [4:0] pad_img3_45_address0;
output   pad_img3_45_ce0;
output   pad_img3_45_we0;
output  [31:0] pad_img3_45_d0;
output  [4:0] pad_img3_46_address0;
output   pad_img3_46_ce0;
output   pad_img3_46_we0;
output  [31:0] pad_img3_46_d0;
output  [4:0] pad_img3_47_address0;
output   pad_img3_47_ce0;
output   pad_img3_47_we0;
output  [31:0] pad_img3_47_d0;
output  [4:0] pad_img3_48_address0;
output   pad_img3_48_ce0;
output   pad_img3_48_we0;
output  [31:0] pad_img3_48_d0;

reg ap_idle;
reg pad_img0_ce0;
reg pad_img1_ce0;
reg pad_img1_we0;
reg pad_img2_ce0;
reg pad_img2_we0;
reg pad_img3_ce0;
reg pad_img3_we0;
reg pad_img3_1_ce0;
reg pad_img3_1_we0;
reg pad_img3_2_ce0;
reg pad_img3_2_we0;
reg pad_img3_3_ce0;
reg pad_img3_3_we0;
reg pad_img3_4_ce0;
reg pad_img3_4_we0;
reg pad_img3_5_ce0;
reg pad_img3_5_we0;
reg pad_img3_6_ce0;
reg pad_img3_6_we0;
reg pad_img3_7_ce0;
reg pad_img3_7_we0;
reg pad_img3_8_ce0;
reg pad_img3_8_we0;
reg pad_img3_9_ce0;
reg pad_img3_9_we0;
reg pad_img3_10_ce0;
reg pad_img3_10_we0;
reg pad_img3_11_ce0;
reg pad_img3_11_we0;
reg pad_img3_12_ce0;
reg pad_img3_12_we0;
reg pad_img3_13_ce0;
reg pad_img3_13_we0;
reg pad_img3_14_ce0;
reg pad_img3_14_we0;
reg pad_img3_15_ce0;
reg pad_img3_15_we0;
reg pad_img3_16_ce0;
reg pad_img3_16_we0;
reg pad_img3_17_ce0;
reg pad_img3_17_we0;
reg pad_img3_18_ce0;
reg pad_img3_18_we0;
reg pad_img3_19_ce0;
reg pad_img3_19_we0;
reg pad_img3_20_ce0;
reg pad_img3_20_we0;
reg pad_img3_21_ce0;
reg pad_img3_21_we0;
reg pad_img3_22_ce0;
reg pad_img3_22_we0;
reg pad_img3_23_ce0;
reg pad_img3_23_we0;
reg pad_img3_24_ce0;
reg pad_img3_24_we0;
reg pad_img3_25_ce0;
reg pad_img3_25_we0;
reg pad_img3_26_ce0;
reg pad_img3_26_we0;
reg pad_img3_27_ce0;
reg pad_img3_27_we0;
reg pad_img3_28_ce0;
reg pad_img3_28_we0;
reg pad_img3_29_ce0;
reg pad_img3_29_we0;
reg pad_img3_30_ce0;
reg pad_img3_30_we0;
reg pad_img3_31_ce0;
reg pad_img3_31_we0;
reg pad_img3_32_ce0;
reg pad_img3_32_we0;
reg pad_img3_33_ce0;
reg pad_img3_33_we0;
reg pad_img3_34_ce0;
reg pad_img3_34_we0;
reg pad_img3_35_ce0;
reg pad_img3_35_we0;
reg pad_img3_36_ce0;
reg pad_img3_36_we0;
reg pad_img3_37_ce0;
reg pad_img3_37_we0;
reg pad_img3_38_ce0;
reg pad_img3_38_we0;
reg pad_img3_39_ce0;
reg pad_img3_39_we0;
reg pad_img3_40_ce0;
reg pad_img3_40_we0;
reg pad_img3_41_ce0;
reg pad_img3_41_we0;
reg pad_img3_42_ce0;
reg pad_img3_42_we0;
reg pad_img3_43_ce0;
reg pad_img3_43_we0;
reg pad_img3_44_ce0;
reg pad_img3_44_we0;
reg pad_img3_45_ce0;
reg pad_img3_45_we0;
reg pad_img3_46_ce0;
reg pad_img3_46_we0;
reg pad_img3_47_ce0;
reg pad_img3_47_we0;
reg pad_img3_48_ce0;
reg pad_img3_48_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln86_fu_882_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] select_ln86_fu_912_p3;
reg   [5:0] select_ln86_reg_1160;
wire   [5:0] select_ln86_1_fu_920_p3;
reg   [5:0] select_ln86_1_reg_1167;
wire   [63:0] zext_ln90_2_fu_1041_p1;
reg   [63:0] zext_ln90_2_reg_1175;
wire   [4:0] add_ln92_1_fu_1069_p2;
reg   [4:0] add_ln92_1_reg_1186;
reg   [4:0] add_ln92_1_reg_1186_pp0_iter2_reg;
reg   [4:0] add_ln92_1_reg_1186_pp0_iter3_reg;
reg   [4:0] add_ln92_1_reg_1186_pp0_iter4_reg;
reg   [4:0] add_ln92_1_reg_1186_pp0_iter5_reg;
reg   [4:0] add_ln92_1_reg_1186_pp0_iter6_reg;
reg   [4:0] add_ln92_1_reg_1186_pp0_iter7_reg;
reg   [4:0] add_ln92_1_reg_1186_pp0_iter8_reg;
reg   [31:0] pad_img0_load_reg_1191;
reg   [31:0] pad_img0_load_reg_1191_pp0_iter3_reg;
reg   [31:0] pad_img0_load_reg_1191_pp0_iter4_reg;
reg   [31:0] pad_img0_load_reg_1191_pp0_iter5_reg;
reg   [31:0] pad_img0_load_reg_1191_pp0_iter6_reg;
reg   [31:0] pad_img0_load_reg_1191_pp0_iter7_reg;
reg   [31:0] pad_img0_load_reg_1191_pp0_iter8_reg;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln92_2_fu_1079_p1;
reg   [5:0] j_fu_174;
wire   [5:0] add_ln88_fu_940_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_j_load;
reg   [5:0] i_fu_178;
reg   [5:0] ap_sig_allocacmp_i_load;
reg   [10:0] indvar_flatten6_fu_182;
wire   [10:0] add_ln86_1_fu_888_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten6_load;
wire   [2:0] trunc_ln86_fu_1075_p1;
wire   [2:0] trunc_ln88_fu_1131_p1;
wire   [0:0] icmp_ln88_fu_906_p2;
wire   [5:0] add_ln86_fu_900_p2;
wire   [5:0] grp_fu_928_p0;
wire   [3:0] grp_fu_928_p1;
wire   [3:0] grp_fu_934_p1;
wire   [6:0] tmp_374_fu_968_p3;
wire   [10:0] tmp_s_fu_961_p3;
wire   [10:0] zext_ln90_fu_975_p1;
wire   [5:0] mul_ln86_fu_988_p0;
wire   [7:0] mul_ln86_fu_988_p1;
wire   [12:0] mul_ln86_fu_988_p2;
wire   [3:0] udiv_ln_cast1_fu_1004_p4;
wire   [2:0] udiv_ln_cast_fu_994_p4;
wire   [4:0] tmp_375_fu_1018_p3;
wire   [4:0] zext_ln92_fu_1014_p1;
wire   [10:0] add_ln90_fu_979_p2;
wire   [10:0] zext_ln90_1_fu_1032_p1;
wire   [10:0] add_ln90_1_fu_1035_p2;
wire   [5:0] mul_ln88_fu_1049_p0;
wire   [7:0] mul_ln88_fu_1049_p1;
wire   [12:0] mul_ln88_fu_1049_p2;
wire   [3:0] udiv_ln3_cast_fu_1055_p4;
wire   [4:0] add_ln92_fu_1026_p2;
wire   [4:0] zext_ln92_1_fu_1065_p1;
wire   [2:0] grp_fu_928_p2;
wire   [2:0] grp_fu_934_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [12:0] mul_ln86_fu_988_p00;
wire   [12:0] mul_ln88_fu_1049_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 j_fu_174 = 6'd0;
#0 i_fu_178 = 6'd0;
#0 indvar_flatten6_fu_182 = 11'd0;
#0 ap_done_reg = 1'b0;
end

cnn_urem_6ns_4ns_3_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
urem_6ns_4ns_3_10_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_928_p0),
    .din1(grp_fu_928_p1),
    .ce(1'b1),
    .dout(grp_fu_928_p2)
);

cnn_urem_6ns_4ns_3_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
urem_6ns_4ns_3_10_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln86_fu_912_p3),
    .din1(grp_fu_934_p1),
    .ce(1'b1),
    .dout(grp_fu_934_p2)
);

cnn_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U7(
    .din0(mul_ln86_fu_988_p0),
    .din1(mul_ln86_fu_988_p1),
    .dout(mul_ln86_fu_988_p2)
);

cnn_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U8(
    .din0(mul_ln88_fu_1049_p0),
    .din1(mul_ln88_fu_1049_p1),
    .dout(mul_ln88_fu_1049_p2)
);

cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln86_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_178 <= select_ln86_1_fu_920_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_178 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln86_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_182 <= add_ln86_1_fu_888_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_182 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln86_fu_882_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_174 <= add_ln88_fu_940_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_174 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln92_1_reg_1186 <= add_ln92_1_fu_1069_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln86_1_reg_1167 <= select_ln86_1_fu_920_p3;
        select_ln86_reg_1160 <= select_ln86_fu_912_p3;
        zext_ln90_2_reg_1175[10 : 0] <= zext_ln90_2_fu_1041_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln92_1_reg_1186_pp0_iter2_reg <= add_ln92_1_reg_1186;
        add_ln92_1_reg_1186_pp0_iter3_reg <= add_ln92_1_reg_1186_pp0_iter2_reg;
        add_ln92_1_reg_1186_pp0_iter4_reg <= add_ln92_1_reg_1186_pp0_iter3_reg;
        add_ln92_1_reg_1186_pp0_iter5_reg <= add_ln92_1_reg_1186_pp0_iter4_reg;
        add_ln92_1_reg_1186_pp0_iter6_reg <= add_ln92_1_reg_1186_pp0_iter5_reg;
        add_ln92_1_reg_1186_pp0_iter7_reg <= add_ln92_1_reg_1186_pp0_iter6_reg;
        add_ln92_1_reg_1186_pp0_iter8_reg <= add_ln92_1_reg_1186_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        pad_img0_load_reg_1191 <= pad_img0_q0;
        pad_img0_load_reg_1191_pp0_iter3_reg <= pad_img0_load_reg_1191;
        pad_img0_load_reg_1191_pp0_iter4_reg <= pad_img0_load_reg_1191_pp0_iter3_reg;
        pad_img0_load_reg_1191_pp0_iter5_reg <= pad_img0_load_reg_1191_pp0_iter4_reg;
        pad_img0_load_reg_1191_pp0_iter6_reg <= pad_img0_load_reg_1191_pp0_iter5_reg;
        pad_img0_load_reg_1191_pp0_iter7_reg <= pad_img0_load_reg_1191_pp0_iter6_reg;
        pad_img0_load_reg_1191_pp0_iter8_reg <= pad_img0_load_reg_1191_pp0_iter7_reg;
    end
end

always @ (*) begin
    if (((icmp_ln86_fu_882_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 6'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_178;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_182;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 6'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_174;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pad_img0_ce0 = 1'b1;
    end else begin
        pad_img0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pad_img1_ce0 = 1'b1;
    end else begin
        pad_img1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pad_img1_we0 = 1'b1;
    end else begin
        pad_img1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pad_img2_ce0 = 1'b1;
    end else begin
        pad_img2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pad_img2_we0 = 1'b1;
    end else begin
        pad_img2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_10_ce0 = 1'b1;
    end else begin
        pad_img3_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd3) & (trunc_ln86_fu_1075_p1 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_10_we0 = 1'b1;
    end else begin
        pad_img3_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_11_ce0 = 1'b1;
    end else begin
        pad_img3_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd4) & (trunc_ln86_fu_1075_p1 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_11_we0 = 1'b1;
    end else begin
        pad_img3_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_12_ce0 = 1'b1;
    end else begin
        pad_img3_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd5) & (trunc_ln86_fu_1075_p1 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_12_we0 = 1'b1;
    end else begin
        pad_img3_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_13_ce0 = 1'b1;
    end else begin
        pad_img3_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd6) & (trunc_ln86_fu_1075_p1 == 3'd1)) | ((trunc_ln88_fu_1131_p1 == 3'd7) & (trunc_ln86_fu_1075_p1 == 3'd1))))) begin
        pad_img3_13_we0 = 1'b1;
    end else begin
        pad_img3_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_14_ce0 = 1'b1;
    end else begin
        pad_img3_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd0) & (trunc_ln86_fu_1075_p1 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_14_we0 = 1'b1;
    end else begin
        pad_img3_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_15_ce0 = 1'b1;
    end else begin
        pad_img3_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd1) & (trunc_ln86_fu_1075_p1 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_15_we0 = 1'b1;
    end else begin
        pad_img3_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_16_ce0 = 1'b1;
    end else begin
        pad_img3_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd2) & (trunc_ln86_fu_1075_p1 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_16_we0 = 1'b1;
    end else begin
        pad_img3_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_17_ce0 = 1'b1;
    end else begin
        pad_img3_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd3) & (trunc_ln86_fu_1075_p1 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_17_we0 = 1'b1;
    end else begin
        pad_img3_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_18_ce0 = 1'b1;
    end else begin
        pad_img3_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd4) & (trunc_ln86_fu_1075_p1 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_18_we0 = 1'b1;
    end else begin
        pad_img3_18_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_19_ce0 = 1'b1;
    end else begin
        pad_img3_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd5) & (trunc_ln86_fu_1075_p1 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_19_we0 = 1'b1;
    end else begin
        pad_img3_19_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_1_ce0 = 1'b1;
    end else begin
        pad_img3_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd1) & (trunc_ln86_fu_1075_p1 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_1_we0 = 1'b1;
    end else begin
        pad_img3_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_20_ce0 = 1'b1;
    end else begin
        pad_img3_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd6) & (trunc_ln86_fu_1075_p1 == 3'd2)) | ((trunc_ln88_fu_1131_p1 == 3'd7) & (trunc_ln86_fu_1075_p1 == 3'd2))))) begin
        pad_img3_20_we0 = 1'b1;
    end else begin
        pad_img3_20_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_21_ce0 = 1'b1;
    end else begin
        pad_img3_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd0) & (trunc_ln86_fu_1075_p1 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_21_we0 = 1'b1;
    end else begin
        pad_img3_21_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_22_ce0 = 1'b1;
    end else begin
        pad_img3_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd1) & (trunc_ln86_fu_1075_p1 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_22_we0 = 1'b1;
    end else begin
        pad_img3_22_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_23_ce0 = 1'b1;
    end else begin
        pad_img3_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd2) & (trunc_ln86_fu_1075_p1 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_23_we0 = 1'b1;
    end else begin
        pad_img3_23_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_24_ce0 = 1'b1;
    end else begin
        pad_img3_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd3) & (trunc_ln86_fu_1075_p1 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_24_we0 = 1'b1;
    end else begin
        pad_img3_24_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_25_ce0 = 1'b1;
    end else begin
        pad_img3_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd4) & (trunc_ln86_fu_1075_p1 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_25_we0 = 1'b1;
    end else begin
        pad_img3_25_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_26_ce0 = 1'b1;
    end else begin
        pad_img3_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd5) & (trunc_ln86_fu_1075_p1 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_26_we0 = 1'b1;
    end else begin
        pad_img3_26_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_27_ce0 = 1'b1;
    end else begin
        pad_img3_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd6) & (trunc_ln86_fu_1075_p1 == 3'd3)) | ((trunc_ln88_fu_1131_p1 == 3'd7) & (trunc_ln86_fu_1075_p1 == 3'd3))))) begin
        pad_img3_27_we0 = 1'b1;
    end else begin
        pad_img3_27_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_28_ce0 = 1'b1;
    end else begin
        pad_img3_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd0) & (trunc_ln86_fu_1075_p1 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_28_we0 = 1'b1;
    end else begin
        pad_img3_28_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_29_ce0 = 1'b1;
    end else begin
        pad_img3_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd1) & (trunc_ln86_fu_1075_p1 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_29_we0 = 1'b1;
    end else begin
        pad_img3_29_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_2_ce0 = 1'b1;
    end else begin
        pad_img3_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd2) & (trunc_ln86_fu_1075_p1 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_2_we0 = 1'b1;
    end else begin
        pad_img3_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_30_ce0 = 1'b1;
    end else begin
        pad_img3_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd2) & (trunc_ln86_fu_1075_p1 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_30_we0 = 1'b1;
    end else begin
        pad_img3_30_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_31_ce0 = 1'b1;
    end else begin
        pad_img3_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd3) & (trunc_ln86_fu_1075_p1 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_31_we0 = 1'b1;
    end else begin
        pad_img3_31_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_32_ce0 = 1'b1;
    end else begin
        pad_img3_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd4) & (trunc_ln86_fu_1075_p1 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_32_we0 = 1'b1;
    end else begin
        pad_img3_32_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_33_ce0 = 1'b1;
    end else begin
        pad_img3_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd5) & (trunc_ln86_fu_1075_p1 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_33_we0 = 1'b1;
    end else begin
        pad_img3_33_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_34_ce0 = 1'b1;
    end else begin
        pad_img3_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd6) & (trunc_ln86_fu_1075_p1 == 3'd4)) | ((trunc_ln88_fu_1131_p1 == 3'd7) & (trunc_ln86_fu_1075_p1 == 3'd4))))) begin
        pad_img3_34_we0 = 1'b1;
    end else begin
        pad_img3_34_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_35_ce0 = 1'b1;
    end else begin
        pad_img3_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd0) & (trunc_ln86_fu_1075_p1 == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_35_we0 = 1'b1;
    end else begin
        pad_img3_35_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_36_ce0 = 1'b1;
    end else begin
        pad_img3_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd1) & (trunc_ln86_fu_1075_p1 == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_36_we0 = 1'b1;
    end else begin
        pad_img3_36_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_37_ce0 = 1'b1;
    end else begin
        pad_img3_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd2) & (trunc_ln86_fu_1075_p1 == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_37_we0 = 1'b1;
    end else begin
        pad_img3_37_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_38_ce0 = 1'b1;
    end else begin
        pad_img3_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd3) & (trunc_ln86_fu_1075_p1 == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_38_we0 = 1'b1;
    end else begin
        pad_img3_38_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_39_ce0 = 1'b1;
    end else begin
        pad_img3_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd4) & (trunc_ln86_fu_1075_p1 == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_39_we0 = 1'b1;
    end else begin
        pad_img3_39_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_3_ce0 = 1'b1;
    end else begin
        pad_img3_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd3) & (trunc_ln86_fu_1075_p1 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_3_we0 = 1'b1;
    end else begin
        pad_img3_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_40_ce0 = 1'b1;
    end else begin
        pad_img3_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd5) & (trunc_ln86_fu_1075_p1 == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_40_we0 = 1'b1;
    end else begin
        pad_img3_40_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_41_ce0 = 1'b1;
    end else begin
        pad_img3_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd6) & (trunc_ln86_fu_1075_p1 == 3'd5)) | ((trunc_ln88_fu_1131_p1 == 3'd7) & (trunc_ln86_fu_1075_p1 == 3'd5))))) begin
        pad_img3_41_we0 = 1'b1;
    end else begin
        pad_img3_41_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_42_ce0 = 1'b1;
    end else begin
        pad_img3_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd0) & (trunc_ln86_fu_1075_p1 == 3'd6)) | ((trunc_ln88_fu_1131_p1 == 3'd0) & (trunc_ln86_fu_1075_p1 == 3'd7))))) begin
        pad_img3_42_we0 = 1'b1;
    end else begin
        pad_img3_42_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_43_ce0 = 1'b1;
    end else begin
        pad_img3_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd1) & (trunc_ln86_fu_1075_p1 == 3'd6)) | ((trunc_ln88_fu_1131_p1 == 3'd1) & (trunc_ln86_fu_1075_p1 == 3'd7))))) begin
        pad_img3_43_we0 = 1'b1;
    end else begin
        pad_img3_43_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_44_ce0 = 1'b1;
    end else begin
        pad_img3_44_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd2) & (trunc_ln86_fu_1075_p1 == 3'd6)) | ((trunc_ln88_fu_1131_p1 == 3'd2) & (trunc_ln86_fu_1075_p1 == 3'd7))))) begin
        pad_img3_44_we0 = 1'b1;
    end else begin
        pad_img3_44_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_45_ce0 = 1'b1;
    end else begin
        pad_img3_45_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd3) & (trunc_ln86_fu_1075_p1 == 3'd6)) | ((trunc_ln88_fu_1131_p1 == 3'd3) & (trunc_ln86_fu_1075_p1 == 3'd7))))) begin
        pad_img3_45_we0 = 1'b1;
    end else begin
        pad_img3_45_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_46_ce0 = 1'b1;
    end else begin
        pad_img3_46_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd4) & (trunc_ln86_fu_1075_p1 == 3'd6)) | ((trunc_ln88_fu_1131_p1 == 3'd4) & (trunc_ln86_fu_1075_p1 == 3'd7))))) begin
        pad_img3_46_we0 = 1'b1;
    end else begin
        pad_img3_46_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_47_ce0 = 1'b1;
    end else begin
        pad_img3_47_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd5) & (trunc_ln86_fu_1075_p1 == 3'd6)) | ((trunc_ln88_fu_1131_p1 == 3'd5) & (trunc_ln86_fu_1075_p1 == 3'd7))))) begin
        pad_img3_47_we0 = 1'b1;
    end else begin
        pad_img3_47_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_48_ce0 = 1'b1;
    end else begin
        pad_img3_48_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((((trunc_ln88_fu_1131_p1 == 3'd6) & (trunc_ln86_fu_1075_p1 == 3'd7)) | ((trunc_ln88_fu_1131_p1 == 3'd7) & (trunc_ln86_fu_1075_p1 == 3'd7))) | ((trunc_ln88_fu_1131_p1 == 3'd7) & (trunc_ln86_fu_1075_p1 == 3'd6))) | ((trunc_ln88_fu_1131_p1 == 3'd6) & (trunc_ln86_fu_1075_p1 == 3'd6))))) begin
        pad_img3_48_we0 = 1'b1;
    end else begin
        pad_img3_48_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_4_ce0 = 1'b1;
    end else begin
        pad_img3_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd4) & (trunc_ln86_fu_1075_p1 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_4_we0 = 1'b1;
    end else begin
        pad_img3_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_5_ce0 = 1'b1;
    end else begin
        pad_img3_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd5) & (trunc_ln86_fu_1075_p1 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_5_we0 = 1'b1;
    end else begin
        pad_img3_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_6_ce0 = 1'b1;
    end else begin
        pad_img3_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (((trunc_ln88_fu_1131_p1 == 3'd6) & (trunc_ln86_fu_1075_p1 == 3'd0)) | ((trunc_ln88_fu_1131_p1 == 3'd7) & (trunc_ln86_fu_1075_p1 == 3'd0))))) begin
        pad_img3_6_we0 = 1'b1;
    end else begin
        pad_img3_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_7_ce0 = 1'b1;
    end else begin
        pad_img3_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd0) & (trunc_ln86_fu_1075_p1 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_7_we0 = 1'b1;
    end else begin
        pad_img3_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_8_ce0 = 1'b1;
    end else begin
        pad_img3_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd1) & (trunc_ln86_fu_1075_p1 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_8_we0 = 1'b1;
    end else begin
        pad_img3_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_9_ce0 = 1'b1;
    end else begin
        pad_img3_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd2) & (trunc_ln86_fu_1075_p1 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_9_we0 = 1'b1;
    end else begin
        pad_img3_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_ce0 = 1'b1;
    end else begin
        pad_img3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln88_fu_1131_p1 == 3'd0) & (trunc_ln86_fu_1075_p1 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        pad_img3_we0 = 1'b1;
    end else begin
        pad_img3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln86_1_fu_888_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 11'd1);

assign add_ln86_fu_900_p2 = (ap_sig_allocacmp_i_load + 6'd1);

assign add_ln88_fu_940_p2 = (select_ln86_fu_912_p3 + 6'd1);

assign add_ln90_1_fu_1035_p2 = (add_ln90_fu_979_p2 + zext_ln90_1_fu_1032_p1);

assign add_ln90_fu_979_p2 = (tmp_s_fu_961_p3 + zext_ln90_fu_975_p1);

assign add_ln92_1_fu_1069_p2 = (add_ln92_fu_1026_p2 + zext_ln92_1_fu_1065_p1);

assign add_ln92_fu_1026_p2 = (tmp_375_fu_1018_p3 + zext_ln92_fu_1014_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_928_p0 = ((icmp_ln88_fu_906_p2[0:0] == 1'b1) ? add_ln86_fu_900_p2 : ap_sig_allocacmp_i_load);

assign grp_fu_928_p1 = 6'd7;

assign grp_fu_934_p1 = 6'd7;

assign icmp_ln86_fu_882_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 11'd1156) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_906_p2 = ((ap_sig_allocacmp_j_load == 6'd34) ? 1'b1 : 1'b0);

assign mul_ln86_fu_988_p0 = mul_ln86_fu_988_p00;

assign mul_ln86_fu_988_p00 = select_ln86_1_reg_1167;

assign mul_ln86_fu_988_p1 = 13'd74;

assign mul_ln88_fu_1049_p0 = mul_ln88_fu_1049_p00;

assign mul_ln88_fu_1049_p00 = select_ln86_reg_1160;

assign mul_ln88_fu_1049_p1 = 13'd74;

assign pad_img0_address0 = zext_ln90_2_fu_1041_p1;

assign pad_img1_address0 = zext_ln90_2_reg_1175;

assign pad_img1_d0 = pad_img0_q0;

assign pad_img2_address0 = zext_ln90_2_reg_1175;

assign pad_img2_d0 = pad_img0_q0;

assign pad_img3_10_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_10_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_11_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_11_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_12_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_12_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_13_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_13_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_14_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_14_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_15_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_15_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_16_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_16_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_17_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_17_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_18_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_18_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_19_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_19_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_1_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_1_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_20_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_20_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_21_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_21_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_22_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_22_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_23_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_23_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_24_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_24_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_25_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_25_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_26_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_26_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_27_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_27_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_28_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_28_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_29_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_29_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_2_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_2_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_30_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_30_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_31_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_31_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_32_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_32_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_33_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_33_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_34_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_34_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_35_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_35_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_36_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_36_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_37_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_37_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_38_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_38_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_39_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_39_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_3_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_3_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_40_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_40_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_41_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_41_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_42_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_42_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_43_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_43_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_44_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_44_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_45_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_45_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_46_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_46_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_47_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_47_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_48_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_48_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_4_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_4_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_5_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_5_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_6_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_6_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_7_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_7_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_8_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_8_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_9_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_9_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign pad_img3_address0 = zext_ln92_2_fu_1079_p1;

assign pad_img3_d0 = pad_img0_load_reg_1191_pp0_iter8_reg;

assign select_ln86_1_fu_920_p3 = ((icmp_ln88_fu_906_p2[0:0] == 1'b1) ? add_ln86_fu_900_p2 : ap_sig_allocacmp_i_load);

assign select_ln86_fu_912_p3 = ((icmp_ln88_fu_906_p2[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_j_load);

assign tmp_374_fu_968_p3 = {{select_ln86_1_reg_1167}, {1'd0}};

assign tmp_375_fu_1018_p3 = {{udiv_ln_cast_fu_994_p4}, {2'd0}};

assign tmp_s_fu_961_p3 = {{select_ln86_1_reg_1167}, {5'd0}};

assign trunc_ln86_fu_1075_p1 = grp_fu_928_p2[2:0];

assign trunc_ln88_fu_1131_p1 = grp_fu_934_p2[2:0];

assign udiv_ln3_cast_fu_1055_p4 = {{mul_ln88_fu_1049_p2[12:9]}};

assign udiv_ln_cast1_fu_1004_p4 = {{mul_ln86_fu_988_p2[12:9]}};

assign udiv_ln_cast_fu_994_p4 = {{mul_ln86_fu_988_p2[11:9]}};

assign zext_ln90_1_fu_1032_p1 = select_ln86_reg_1160;

assign zext_ln90_2_fu_1041_p1 = add_ln90_1_fu_1035_p2;

assign zext_ln90_fu_975_p1 = tmp_374_fu_968_p3;

assign zext_ln92_1_fu_1065_p1 = udiv_ln3_cast_fu_1055_p4;

assign zext_ln92_2_fu_1079_p1 = add_ln92_1_reg_1186_pp0_iter8_reg;

assign zext_ln92_fu_1014_p1 = udiv_ln_cast1_fu_1004_p4;

always @ (posedge ap_clk) begin
    zext_ln90_2_reg_1175[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //cnn_cnn_Pipeline_clone_for_rows_clone_for_cols
